export const interests = [
  { name: 'the future' },
  { name: 'architecture' },
  { name: 'my work' },
  { name: 'your work' },
  { name: 'collaboration' },
  { name: 'dank memes' },
  { name: 'OOP vs. Functional' },
  { name: 'design' },
  { name: 'guitar' },
  { name: 'inspirational people' },
  { name: 'love' },
  { name: 'travel' },
  { name: 'singularity' },
  { name: 'creativity' },
  { name: 'coding' },
  { name: 'mixed, virtual, augmented reality' },
  { name: 'art' },
  { name: 'imagination' },
  { name: 'installation art' },
  { name: 'problem solving' },
  { name: 'space' },
  { name: 'cooking' },
  { name: 'FOMO' },
  { name: 'ontological design' },
  { name: 'flow state' },
  { name: 'foreign languages' },
  { name: 'streaming on the internet' },
  { name: 'video games' },
  { name: 'coffee' },
  { name: 'crypto currency' },
  { name: 'javascript fatigue' },
  { name: 'framework wars' },
  { name: 'blockchain' },
  { name: 'smart contracts' },
  { name: 'just emailing me' },
  { name: 'wasm' },
  { name: 'rust lang' },
  { name: 'ethereum' },
  { name: 'university' },
  { name: 'engineering software' },
  { name: 'game development' },
  { name: 'sound design' },
  { name: 'lofi hiphop' },
];
